# Form implementation generated from reading ui file 'c:\Users\djmin\Downloads\VisStudio\finalproject\VotingApplication.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_VotingApplication(object):
    def setupUi(self, VotingApplication):
        VotingApplication.setObjectName("VotingApplication")
        VotingApplication.resize(250, 225)
        VotingApplication.setMinimumSize(QtCore.QSize(250, 225))
        VotingApplication.setMaximumSize(QtCore.QSize(250, 275))
        self.centralwidget = QtWidgets.QWidget(parent=VotingApplication)
        self.centralwidget.setObjectName("centralwidget")
        self.VotingLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.VotingLabel.setGeometry(QtCore.QRect(60, 10, 131, 21))
        self.VotingLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.VotingLabel.setObjectName("VotingLabel")
        self.IDLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.IDLabel.setGeometry(QtCore.QRect(30, 40, 16, 21))
        self.IDLabel.setObjectName("IDLabel")
        self.IDInput = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.IDInput.setGeometry(QtCore.QRect(50, 40, 161, 20))
        self.IDInput.setObjectName("IDInput")
        self.CandidatesLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.CandidatesLabel.setGeometry(QtCore.QRect(90, 60, 71, 31))
        self.CandidatesLabel.setObjectName("CandidatesLabel")
        self.JaneVote = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.JaneVote.setGeometry(QtCore.QRect(100, 85, 61, 16))
        self.JaneVote.setObjectName("JaneVote")
        self.VotingGroup = QtWidgets.QButtonGroup(VotingApplication)
        self.VotingGroup.setObjectName("VotingGroup")
        self.VotingGroup.addButton(self.JaneVote)
        self.JohnVote = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.JohnVote.setGeometry(QtCore.QRect(100, 105, 61, 16))
        self.JohnVote.setObjectName("JohnVote")
        self.VotingGroup.addButton(self.JohnVote)
        self.SubmitButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.SubmitButton.setGeometry(QtCore.QRect(60, 132, 131, 21))
        self.SubmitButton.setObjectName("SubmitButton")
        self.InfoLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.InfoLabel.setGeometry(QtCore.QRect(20, 155, 211, 21))
        self.InfoLabel.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.InfoLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.InfoLabel.setObjectName("InfoLabel")
        VotingApplication.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=VotingApplication)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 250, 21))
        self.menubar.setObjectName("menubar")
        VotingApplication.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=VotingApplication)
        self.statusbar.setObjectName("statusbar")
        VotingApplication.setStatusBar(self.statusbar)

        self.retranslateUi(VotingApplication)
        QtCore.QMetaObject.connectSlotsByName(VotingApplication)

    def retranslateUi(self, VotingApplication):
        _translate = QtCore.QCoreApplication.translate
        VotingApplication.setWindowTitle(_translate("VotingApplication", "VOTING APPLICATION"))
        self.VotingLabel.setText(_translate("VotingApplication", "VOTING APPLICATION"))
        self.IDLabel.setText(_translate("VotingApplication", "ID"))
        self.CandidatesLabel.setText(_translate("VotingApplication", "CANDIDATES"))
        self.JaneVote.setText(_translate("VotingApplication", "Jane"))
        self.JohnVote.setText(_translate("VotingApplication", "John"))
        self.SubmitButton.setText(_translate("VotingApplication", "SUBMIT VOTE"))
        self.InfoLabel.setText(_translate("VotingApplication", "Input ID and Vote"))
